CREATE TABLE tasks (
    id              NUMBER(19,0)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR2(255)  NOT NULL,
    description     CLOB,
    status          VARCHAR2(50)   DEFAULT 'TODO',
    priority        VARCHAR2(50)   DEFAULT 'MEDIUM',
    assignee        VARCHAR2(100),
    createdby       VARCHAR2(100),
    due_date        TIMESTAMP,
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    updated_at      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    category        VARCHAR2(100),
    tags            VARCHAR2(500),
    estimated_hours NUMBER(8,2),
    actual_hours    NUMBER(8,2),
    programme       VARCHAR2(100),
    project         VARCHAR2(100),
    assetclass      VARCHAR2(100),
    working_group   VARCHAR2(100),
    stakeholder     VARCHAR2(100),
    jira            VARCHAR2(100),
    links           VARCHAR2(255),
    parent_task_id  NUMBER(19,0)   REFERENCES tasks (id),
    custom_field_1  VARCHAR2(255),
    custom_field_2  VARCHAR2(255),
    custom_field_3  VARCHAR2(255),
    custom_field_4  VARCHAR2(255),
    custom_field_5  VARCHAR2(255),
    custom_field_6  VARCHAR2(255),
    custom_field_7  VARCHAR2(255),
    custom_field_8  VARCHAR2(255),
    custom_field_9  VARCHAR2(255),
    custom_field_10 VARCHAR2(255)
);

CREATE INDEX idx_tasks_status    ON tasks (status);
CREATE INDEX idx_tasks_priority  ON tasks (priority);
CREATE INDEX idx_tasks_assignee  ON tasks (assignee);
CREATE INDEX idx_tasks_due_date  ON tasks (due_date);
CREATE INDEX idx_tasks_category  ON tasks (category);
CREATE INDEX idx_tasks_programme ON tasks (programme);
CREATE INDEX idx_tasks_project   ON tasks (project);

CREATE TABLE task_comments (
    id         NUMBER(19,0)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    NUMBER(19,0)  NOT NULL REFERENCES tasks (id),
    content    CLOB          NOT NULL,
    author     VARCHAR2(100),
    created_at TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_comments_task_id ON task_comments (task_id);

CREATE TABLE task_history (
    id          NUMBER(19,0)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     NUMBER(19,0)  NOT NULL REFERENCES tasks (id),
    field_name  VARCHAR2(100),
    old_value   CLOB,
    new_value   CLOB,
    changed_by  VARCHAR2(100),
    changed_at  TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_history_task_id ON task_history (task_id);
