CREATE TABLE projects (
    id          NUMBER(19,0)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(150) NOT NULL UNIQUE,
    description CLOB,
    owner       VARCHAR2(100),
    status      VARCHAR2(30)  DEFAULT 'PLANNING',
    start_date  DATE,
    end_date    DATE,
    created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP,
    updated_at  TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_projects_status ON projects (status);

CREATE TABLE milestones (
    id          NUMBER(19,0)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  NUMBER(19,0)  NOT NULL REFERENCES projects (id),
    name        VARCHAR2(150) NOT NULL,
    description CLOB,
    target_date DATE,
    status      VARCHAR2(30)  DEFAULT 'PENDING',
    created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP,
    updated_at  TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_milestones_project_id ON milestones (project_id);
CREATE INDEX idx_milestones_target_date ON milestones (target_date);
