CREATE TABLE programmes (
    id          NUMBER(19,0)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(150) NOT NULL UNIQUE,
    description CLOB,
    owner       VARCHAR2(100),
    status      VARCHAR2(30)  DEFAULT 'PLANNING',
    start_date  DATE,
    end_date    DATE,
    created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP,
    updated_at  TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_programmes_status ON programmes (status);
