CREATE TABLE task_dependencies (
    id                  NUMBER(19,0)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id             NUMBER(19,0)  NOT NULL REFERENCES tasks (id),
    depends_on_task_id  NUMBER(19,0)  NOT NULL REFERENCES tasks (id),
    created_at          TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_task_dependency UNIQUE (task_id, depends_on_task_id),
    CONSTRAINT chk_task_dependency_not_self CHECK (task_id <> depends_on_task_id)
);

CREATE INDEX idx_task_dependencies_task_id ON task_dependencies (task_id);
CREATE INDEX idx_task_dependencies_depends_on ON task_dependencies (depends_on_task_id);
