CREATE TABLE task_templates (
    id              NUMBER(19,0)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(150)  NOT NULL UNIQUE,
    title           VARCHAR2(255)  NOT NULL,
    description     CLOB,
    priority        VARCHAR2(50)   DEFAULT 'MEDIUM',
    category        VARCHAR2(100),
    tags            VARCHAR2(500),
    estimated_hours NUMBER(8,2),
    programme       VARCHAR2(100),
    project         VARCHAR2(100),
    assetclass      VARCHAR2(100),
    working_group   VARCHAR2(100),
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);
