CREATE TABLE events (
    id          NUMBER(19,0)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR2(200) NOT NULL,
    type        VARCHAR2(40)  DEFAULT 'OTHER',
    description CLOB,
    start_date  DATE NOT NULL,
    end_date    DATE,
    created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP,
    updated_at  TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_events_start_date ON events (start_date);
