#!/usr/bin/env python3
"""
Convert task JSON files from the file-system store to PostgreSQL INSERT statements.

Usage:
    python tasks_to_sql.py [data_dir] [output_file]

    data_dir     - root of the file store (default: ./tasks)
    output_file  - write SQL here instead of stdout (optional)

Directory layout expected under data_dir:
    tasks/      - one JSON file per task  (<id>.json)
    comments/   - one JSON array file per task  (task-<id>.json)
    history/    - one JSON array file per task  (task-<id>.json)
"""

import json
import os
import sys
from pathlib import Path


def esc(value) -> str:
    """Return a SQL literal: NULL, a quoted string, or an unquoted number/boolean."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    # Escape single quotes by doubling them
    return "'" + str(value).replace("'", "''") + "'"


def tags_to_str(tags) -> str:
    if not tags:
        return "NULL"
    return esc(",".join(str(t) for t in tags))


def load_json(path: Path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def task_insert(task: dict) -> str:
    return (
        "INSERT INTO tasks "
        "(id, title, description, status, priority, assignee, createdby, "
        "due_date, created_at, updated_at, tags, jira, programme) "
        "OVERRIDING SYSTEM VALUE VALUES ("
        f"{esc(task.get('id'))}, "
        f"{esc(task.get('title'))}, "
        f"{esc(task.get('description'))}, "
        f"{esc(task.get('status'))}, "
        f"{esc(task.get('priority'))}, "
        f"{esc(task.get('assignee'))}, "
        f"{esc(task.get('createdBy'))}, "
        f"{esc(task.get('dueDate'))}, "
        f"{esc(task.get('createdAt'))}, "
        f"{esc(task.get('updatedAt'))}, "
        f"{tags_to_str(task.get('tags'))}, "
        f"{esc(task.get('jira'))}, "
        f"{esc(task.get('programme'))}"
        ");"
    )


def comment_insert(comment: dict) -> str:
    return (
        "INSERT INTO task_comments (id, task_id, content, author, created_at) "
        "OVERRIDING SYSTEM VALUE VALUES ("
        f"{esc(comment.get('id'))}, "
        f"{esc(comment.get('taskId'))}, "
        f"{esc(comment.get('content'))}, "
        f"{esc(comment.get('author'))}, "
        f"{esc(comment.get('createdAt'))}"
        ");"
    )


def history_insert(entry: dict) -> str:
    return (
        "INSERT INTO task_history (id, task_id, field_name, old_value, new_value, changed_by, changed_at) "
        "OVERRIDING SYSTEM VALUE VALUES ("
        f"{esc(entry.get('id'))}, "
        f"{esc(entry.get('taskId'))}, "
        f"{esc(entry.get('fieldName'))}, "
        f"{esc(entry.get('oldValue'))}, "
        f"{esc(entry.get('newValue'))}, "
        f"{esc(entry.get('changedBy'))}, "
        f"{esc(entry.get('changedAt'))}"
        ");"
    )


def generate_sql(data_dir: Path) -> list[str]:
    lines = [
        "-- Generated by tasks_to_sql.py",
        "-- PostgreSQL INSERT statements for tasks, task_comments, task_history",
        "",
        "BEGIN;",
        "",
    ]

    # --- tasks ---
    tasks_dir = data_dir / "tasks"
    task_files = sorted(tasks_dir.glob("*.json")) if tasks_dir.exists() else []
    if task_files:
        lines.append("-- tasks")
        for path in task_files:
            task = load_json(path)
            lines.append(task_insert(task))
        lines.append("")

    # --- comments ---
    comments_dir = data_dir / "comments"
    comment_files = sorted(comments_dir.glob("task-*.json")) if comments_dir.exists() else []
    if comment_files:
        lines.append("-- task_comments")
        for path in comment_files:
            entries = load_json(path)
            if isinstance(entries, list):
                for entry in entries:
                    lines.append(comment_insert(entry))
            else:
                lines.append(comment_insert(entries))
        lines.append("")

    # --- history ---
    history_dir = data_dir / "history"
    history_files = sorted(history_dir.glob("task-*.json")) if history_dir.exists() else []
    if history_files:
        lines.append("-- task_history")
        for path in history_files:
            entries = load_json(path)
            if isinstance(entries, list):
                for entry in entries:
                    lines.append(history_insert(entry))
            else:
                lines.append(history_insert(entries))
        lines.append("")

    # Reset sequences so future inserts don't collide with imported IDs
    lines += [
        "-- Reset sequences to max imported id",
        "SELECT setval('tasks_id_seq',       COALESCE((SELECT MAX(id) FROM tasks), 1));",
        "SELECT setval('task_comments_id_seq', COALESCE((SELECT MAX(id) FROM task_comments), 1));",
        "SELECT setval('task_history_id_seq',  COALESCE((SELECT MAX(id) FROM task_history), 1));",
        "",
        "COMMIT;",
    ]
    return lines


def main():
    data_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parent / "tasks"
    output_file = sys.argv[2] if len(sys.argv) > 2 else None

    if not data_dir.exists():
        print(f"Error: directory not found: {data_dir}", file=sys.stderr)
        sys.exit(1)

    sql_lines = generate_sql(data_dir)
    sql = "\n".join(sql_lines) + "\n"

    if output_file:
        Path(output_file).write_text(sql, encoding="utf-8")
        print(f"SQL written to {output_file}")
    else:
        print(sql)


if __name__ == "__main__":
    main()
